name: ecg-anomaly-detection
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch
  - torchvision  
# - cudatoolkit=11.7  when using GPU
  - matplotlib
  - seaborn
  - tqdm
  - wfdb
  - scikit-image  
  - pip
  - pip:
      - dash
      - plotly
#     - windows-curses  just if using dash in Windows terminal
      - wfdb      
