name: ecg-anomaly-detection
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch
  - torchvision  # if you need image utilities; can omit if unused
  - cudatoolkit=11.7  # or your local CUDA version; omit if CPU-only
  - matplotlib
  - seaborn
  - tqdm
  - wfdb
  - scikit-image  # for any additional signal/image needs
  - pip
  - pip:
      - dash
      - plotly
      - windows-curses  # if using dash in Windows terminal
      - wfdb      # also available via pip on some platforms
